image:
  repository: artifactory.dagility.com/docker/gh-bs-backend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: gh-bs-backend-habitat-development.dagility.com
    paths:
    - /
serviceAccount:
  create: false
